# Generated by Django 4.0.3 on 2022-04-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lanaguage',
            new_name='language',
        ),
    ]
